import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,

bag1,
bag2,
bag3,
bag4,
bag5,
cap1,
cap2,
cap3,
cap4,
cap5,
glass1,
glass2,
glass3,
glass4,
hp1,
hp2,
hp3,
hp4,
hp5,
hp6,
hp7,
hp8,
phone1,
phone2,
phone3,
phone4,
phone5,
phone6,
phone7,
ts1,
ts2,
ts3,
ts4,
ts5,
ts6,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  }
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    price: "350",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    price: "1800",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "250",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    price: "2200",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  //this is new


  {
    _id: 7001,
    img: phone1,
    productName: "Samsung Galaxy S24 Ultra",
    price: "1,10,0000",
    color: "Blank and White",
    badge: true,
    rating: 4,
    des: "This is Des",
    categories: "Electronics",
  },
  {
    _id: 5002,
    img: phone2,
    productName: "Samsung Galaxy S23 Ultra",
    price: " 98000",
    color: "Blank and White",
    badge: true,
    rating: 2,
    des: "This is Des",
    categories: "Electronics",
  },
  {
    _id: 5003,
    img: phone3,
    productName: "Samsung Galaxy S24",
    price: "  89000",
    color: "Blank and White",
    badge: true,
    rating: 3,
    des: "This is Des",
    categories: "electronics",
  },
  {
    _id: 5004,
    img: phone4,
    productName: "Pixel 8 Pro",
    price: " 900000",
    color: "Blank and White",
    badge: true,
    rating: 5,
    des: "This is Des",
    categories: "electronics",
  },
  {
    _id: 5005,
    img: phone5,
    productName: "Pixel 8 Pro",
    price: " 900000",
    color: "Blank and White",
    badge: true,
    rating: 5,
    des: "This is Des",
    categories: "electronics",
  },
  {
    _id: 5006,
    img: phone6,
    productName: "Pixel 8",
    price: " 800000",
    color: "Blank and White",
    badge: true,
    rating: 4,
    des: "This is Des",
    categories: "electronics",
  },
  {
    _id: 5007,
    img: phone7,
    productName: "iPhone 13 pro",
    price: " 1,50,0000",
    color: "Blank and White",
    badge: true,
    rating: 5,
    des: "This is Des",
    categories: "electronics",
  },
  {
    _id: 6001,
    img: ts1,
    productName: "H&M Originals T-Shirt",
    price: " 35000",
    color: "Blank and White",
    badge: true,
    rating: 4,
    des: "This is Des",
    categories: "Clothing",
  },
  {
    _id: 6002,
    img: ts2,
    productName: "H&M Originals T-Shirt",
    price: " 25000",
    color: "Blank and White",
    badge: true,
    rating: 3,
    des: "This is Des",
    categories: "Clothing",
  },
  {
    _id: 6003,
    img: ts3,
    productName: "H&M Originals T-Shirt",
    price: " 45000",
    color: "Blank and White",
    badge: true,
    rating: 5,
    des: "This is Des",
    categories: "Clothing",
  },
  {
    _id: 6004,
    img: ts4,
    productName: "H&M Originals T-Shirt",
    price: " 55000",
    color: "Blank and White",
    badge: true,
    rating: 3,
    des: "This is Des",
    categories: "Clothing",
  },
  {
    _id: 6005,
    img: ts5,
    productName: "H&M Originals T-Shirt",
    price: " 65000",
    color: "Blank and White",
    badge: true,
    rating: 5,
    des: "This is Des",
    categories: "Clothing",
  },
  {
    _id: 6006,
    img: ts6,
    productName: "H&M Originals T-Shirt",
    price: " 35000",
    color: "Blank and White",
    badge: true,
    rating: 2,
    des: "This is Des",
    categories: "Clothing",
  },
  {
    _id: 7001,
    img: hp1,
    productName: "Headphones Originals",
    price: " 35000",
    color: "Blank and White",
    badge: true,
    rating: 2,
    des: "This is Des",
    categories: "Electronics",
  },
  {
    _id: 7002,
    img: hp2,
    productName: "Headphones Originals ",
    price: " 400000",
    color: "Blank and White",
    badge: true,
    rating: 3,
    des: "This is Des",
    categories: "Electronics",
  },
  {
    _id: 7003,
    img: hp3,
    productName: "Headphones Originals ",
    price: " 350000",
    color: "Blank and White",
    badge: true,
    rating: 2,
    des: "This is Des",
    categories: "Electronics",
  },
  {
    _id: 7004,
    img: hp4,
    productName: "Headphones Originals ",
    price: " 500000",
    color: "Blank and White",
    badge: true,
    rating: 4,
    des: "This is Des",
    categories: "Electronics",
  },
  {
    _id: 7005,
    img: hp5,
    productName: "Headphones Originals ",
    price: " 350000",
    color: "Blank and White",
    badge: true,
    rating: 2,
    des: "This is Des",
    categories: "Electronics",
  },
  {
    _id: 7006,
    img: hp6,
    productName: "Headphones Originals ",
    price: " 3500000",
    color: "Blank and White",
    badge: true,
    rating: 2,
    des: "This is Des",
    categories: "Electronics",
  },
  {
    _id: 7007,
    img: hp7,
    productName: "Headphones Originals",
    price: " 700000",
    color: "Blank and White",
    badge: true,
    rating: 4,
    des: "This is Des",
    categories: "Electronics",
  },
  {
    _id: 8001,
    img: hp8,
    productName: "",
    price: "350",
    color: "Blank and White",
    badge: true,
    rating: 2,
    des: "This is Des",
    categories: "Accesories",
  },
  {
    _id: 9001,
    img: bag1,
    productName: "Zara Orginals Bag",
    price: "350000",
    color: "Blank and White",
    badge: true,
    rating: 4,
    des: "This is Des",
    categories: "Accesories",
  },
  {
    _id: 99001,
    img: bag2,
    productName: "Zara Orginals Bag",
    price: "400000",
    color: "Blank and White",
    badge: true,
    rating: 5,
    des: "This is Des",
    categories: "Accesories",
  },
  {
    _id: 98001,
    img: bag3,
    productName: "Zara Orginals Bag",
    price: "500000",
    color: "Blank and White",
    badge: true,
    rating: 4,
    des: "This is Des",
    categories: "Accesories",
  },
  {
    _id: 89001,
    img: bag4,
    productName: "Zara Orginals Bag",
    price: "123350",
    color: "Blank and White",
    badge: true,
    rating: 4,
    des: "This is Des",
    categories: "Accessories",
  },
  {
    _id: 78001,
    img: bag5,
    productName: "Zara Orginals Bag",
    price: "345350",
    color: "Blank and White",
    badge: true,
    rating: 3,
    des: "This is Des",
    categories: "Accesories",
  },
  {
    _id: 12001,
    img: cap1,
    productName: "Urban Monkey Cap Originals",
    price: "350000",
    color: "Blank and White",
    badge: true,
    rating: 3,
    des: "This is Des",
    categories: "Accessories",
  },
  {
    _id: 13001,
    img: cap2,
    productName: "Urban Monkey Cap Originals",
    price: "450000",
    color: "Blank and White",
    badge: true,
    rating: 4,
    des: "This is Des",
    categories: "Accessories",
  },
  {
    _id: 14001,
    img: cap3,
    productName: "Urban Monkey Cap Originals",
    price: "500000",
    color: "Blank and White",
    badge: true,
    rating: 2,
    des: "This is Des",
    categories: "Accessories",
  },
  {
    _id: 15001,
    img: cap4,
    productName: "Urban Monkey Cap Originals",
    price: "325000",
    color: "Blank and White",
    badge: true,
    rating: 5,
    des: "This is Des",
    categories: "Accessories",
  },
  {
    _id: 19001,
    img: cap5,
    productName: "Urban Monkey Cap Originals",
    price: "35000",
    color: "Blank and White",
    badge: true,
    rating: 2,
    des: "This is Des",
    categories: "Accessories",
  },
  {
    _id: 24001,
    img: glass1,
    productName: "Lenskart Originals",
    price: "450000",
    color: "Blank and White",
    badge: true,
    rating: 5,
    des: "This is Des",
    categories: "Accessories",
  },
  {
    _id: 23001,
    img: glass2,
    productName: "Lenskart Originals",
    price: "350000",
    color: "Blank and White",
    badge: true,
    rating: 5,
    des: "This is Des",
    categories: "Accessories",
  },

  {
    _id: 21001,
    img: glass3,
    productName: "Lenskart Originals",
    price: "25000",
    color: "Blank and White",
    badge: true,
    rating: 2,
    des: "This is Des",
    categories: "Accessories",
  },

  {
    _id: 41001,
    img: glass4,
    productName: "Lenskart Originals",
    price: "45000",
    color: "Blank and White",
    badge: true,
    rating: 4,
    des: "This is Des",
    categories: "Accessories",
  },


  // this is old
  {
    _id: 1015,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "600",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
 
  {
    _id: 1018,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "440",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1019,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  
 
  {
    _id: 1024,
    img: spfOne,
    productName: "Cap for Boys",
    price: "350",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "Tea Table",
    price: "1800",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Headphones",
    price: "250",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "Sun glasses",
    price: "2200",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "350",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "1800",
    color: "Gray",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Household materials",
    price: "250",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "2200",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "440",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "cloth Basket",
    price: "800",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "600",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "600",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "600",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "2200",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "440",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "cloth Basket",
    price: "800",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Headphones",
    price: "250",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Sun glasses",
    price: "2200",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "350",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Cap for Boys",
    price: "350",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

];
// =================== PaginationItems End here =================
